version: '3'

services: 

    app:
        build: .
        container_name: movie-recommendation-app
        # volumes:
        #   - ./:/usr/src/app
        networks:
            - proxy-network
        ports:
            - 8000:8000

    reverse-proxy:
        image: nginx:stable-alpine
        volumes: 
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
        ports:
            - 80:80
        networks:
            - proxy-network
        container_name: proxy
        depends_on: 
            - app

networks: 
    proxy-network:
        name: proxy-network